services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\AccountBundle\DataFixtures\:
        resource: '../../src/DataFixtures/*'
        tags: ['doctrine.fixtures.loader']