services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\AccountBundle\EventListener\AccountDoctrineFilterListener:
        tags: ['kernel.event_subscriber']

    Softspring\AccountBundle\Doctrine\EventListener\AccountFilteredEventListener:
        tags:
            - { name: 'doctrine.event_listener', event: prePersist }
