services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\Account\Manager\AccountManagerInterface:
        class: Softspring\AccountBundle\Manager\AccountManager

    Softspring\AccountBundle\Controller\:
        resource: '../../Controller/*'
        public: true
