services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $accountRouteParamName: '%sfs_account.account.route_param_name%'

    Softspring\AccountBundle\EventListener\AccountDoctrineFilterListener:
        tags: ['kernel.event_subscriber']

    Softspring\AccountBundle\Doctrine\EventListener\AccountFilteredEventListener:
        tags: ['doctrine.event_subscriber']
