services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $accountRouteParamName: '%sfs_account.account.route_param_name%'
            $twigAppVariable: '@twig.app_variable'
            $em: '@sfs_account.entity_manager'
            $findParamName: '%sfs_account.account.find_field_name%'

    Softspring\AccountBundle\Manager\AccountManagerInterface:
        class: Softspring\AccountBundle\Manager\AccountManager
        arguments:
            $targetClass: 'Softspring\AccountBundle\Model\AccountInterface'

    Softspring\AccountBundle\Manager\RelationManagerInterface:
        class: Softspring\AccountBundle\Manager\RelationManager

    Softspring\AccountBundle\EventListener\AccountRequestListener:
        tags: ['kernel.event_subscriber']

    Softspring\AccountBundle\EventListener\AccountAccessPermissionListener:
        tags: ['kernel.event_subscriber']

    Softspring\AccountBundle\EventListener\AccountCreateListener:
        tags: ['kernel.event_subscriber']

    Softspring\AccountBundle\EventListener\UserRegisterListener:
        tags: ['kernel.event_subscriber']

    Softspring\AccountBundle\EventListener\AdminAccountDeleteListener:
        tags: ['kernel.event_subscriber']

    Softspring\AccountBundle\EventListener\AdminUserDeleteListener:
        tags: ['kernel.event_subscriber']

    Softspring\AccountBundle\Security\Authorization\Voter\AccountAccessVoter: ~