services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\AccountBundle\Form\Admin\:
        resource: '../../../src/Form/Admin/*'

    Softspring\AccountBundle\Controller\Admin\AccountsController:
        public: true
        tags: ['controller.service_arguments']


    sfs_account.admin.account.controller:
        class: Softspring\Component\CrudlController\Controller\CrudlController
        public: true
        calls:
            - { method: setContainer, arguments: ['@service_container'] }
        arguments:
            $manager: '@Softspring\AccountBundle\Manager\AccountManagerInterface'
            $eventDispatcher: '@event_dispatcher'
            $listFilterForm: '@Softspring\AccountBundle\Form\Admin\AccountListFilterFormInterface'
            $createForm: '@Softspring\AccountBundle\Form\Admin\AccountCreateFormInterface'
            $updateForm: '@Softspring\AccountBundle\Form\Admin\AccountUpdateFormInterface'
            $deleteForm: '@Softspring\AccountBundle\Form\Admin\AccountDeleteFormInterface'
            $config:
                entity_attribute: 'account'
                list:
                    is_granted: 'ROLE_ADMIN_ACCOUNTS_LIST'
                    initialize_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_LIST_INITIALIZE
                    view_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_LIST_VIEW
                    view: '@@SfsAccount/admin/accounts/list.html.twig'
                    view_page: '@@SfsAccount/admin/accounts/list-page.html.twig'
                    entities_attribute: 'accounts'
                update:
                    is_granted: 'ROLE_ADMIN_ACCOUNTS_UPDATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_UPDATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_UPDATE_FORM_VALID
                    success_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_UPDATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_UPDATE_FORM_INVALID
                    view_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_UPDATE_VIEW
                    success_redirect_to: 'sfs_account_admin_accounts_list'
                    view: '@@SfsAccount/admin/accounts/update.html.twig'
                create:
                    is_granted: 'ROLE_ADMIN_ACCOUNTS_CREATE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_CREATE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_CREATE_FORM_VALID
                    success_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_CREATE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_CREATE_FORM_INVALID
                    view_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_CREATE_VIEW
                    success_redirect_to: 'sfs_account_admin_accounts_list'
                    view: '@@SfsAccount/admin/accounts/create.html.twig'
                delete:
                    is_granted: 'ROLE_ADMIN_ACCOUNTS_DELETE'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_DELETE_INITIALIZE
                    form_valid_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_DELETE_FORM_VALID
                    success_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_DELETE_SUCCESS
                    form_invalid_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_DELETE_FORM_INVALID
                    view_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_DELETE_VIEW
                    success_redirect_to: 'sfs_account_admin_accounts_list'
                    view: '@@SfsAccount/admin/accounts/delete.html.twig'
                read:
                    is_granted: 'ROLE_ADMIN_ACCOUNTS_DETAILS'
                    param_converter_key: 'id'
                    initialize_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_DETAILS_INITIALIZE
                    view_event_name: !php/const Softspring\AccountBundle\SfsAccountEvents::ADMIN_ACCOUNTS_DETAILS_VIEW
                    view: '@@SfsAccount/admin/accounts/details.html.twig'