sfs_account_register:
    path: /
    controller: Softspring\AccountBundle\Controller\RegisterController::register

sfs_account_register_success:
    path: /{account}/welcome
    controller: Softspring\AccountBundle\Controller\RegisterController::success