sfs_account_admin_accounts_list:
    controller: Softspring\AccountBundle\Controller\Admin\AccountsController::list
    path: /

sfs_account_admin_accounts_create:
    controller: Softspring\AccountBundle\Controller\Admin\AccountsController::create
    path: /create

sfs_account_admin_accounts_details:
    controller: Softspring\AccountBundle\Controller\Admin\AccountsController::details
    path: /{account}/details

sfs_account_admin_accounts_update:
    controller: Softspring\AccountBundle\Controller\Admin\AccountsController::update
    path: /{account}/update

sfs_account_admin_accounts_delete:
    controller: Softspring\AccountBundle\Controller\Admin\AccountsController::delete
    path: /{account}/delete

sfs_account_admin_accounts_count_widget:
    controller: Softspring\AccountBundle\Controller\Admin\AccountsController::accountsCountWidget
    path: /_widget/accounts-count