security:
    role_hierarchy:
        ROLE_SFS_ACCOUNT_ADMIN_ACCOUNTS_RO:
            - PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_LIST
            - PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_DETAILS
        ROLE_SFS_ACCOUNT_ADMIN_ACCOUNTS_RW:
            - ROLE_SFS_ACCOUNT_ADMIN_ACCOUNTS_RO
            - PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_UPDATE
            - PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_DELETE

        # DEPRECATED ROLES, WILL BE REMOVED IN 6.0
        # 5.1 REQUIRES PERMISSIONS-BUNDLE
        PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_LIST:
            - ROLE_ADMIN_ACCOUNTS_LIST
        PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_DETAILS:
            - ROLE_ADMIN_ACCOUNTS_DETAILS
        PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_UPDATE:
            - ROLE_ADMIN_ACCOUNTS_UPDATE
        PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_DELETE:
            - ROLE_ADMIN_ACCOUNTS_DELETE
        ROLE_ADMIN_ACCOUNTS_RO:
            - ROLE_SFS_ACCOUNT_ADMIN_ACCOUNTS_RO
        ROLE_ADMIN_ACCOUNTS_RW:
            - ROLE_SFS_ACCOUNT_ADMIN_ACCOUNTS_RW