security:
    role_hierarchy:
        ROLE_ADMIN_ACCOUNTS_RO:
            - ROLE_ADMIN_ACCOUNTS_LIST
            - ROLE_ADMIN_ACCOUNTS_DETAILS
        ROLE_ADMIN_ACCOUNTS_RW:
            - ROLE_ADMIN_ACCOUNTS_RO
            - ROLE_ADMIN_ACCOUNTS_UPDATE
            - ROLE_ADMIN_ACCOUNTS_DELETE

        # ROLE_ADMIN_ACCOUNTS_CREATE