security:
    role_hierarchy:
        ROLE_SFS_ACCOUNT_ADMIN_ACCOUNTS_RO:
            - PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_LIST
            - PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_DETAILS
        ROLE_SFS_ACCOUNT_ADMIN_ACCOUNTS_RW:
            - ROLE_SFS_ACCOUNT_ADMIN_ACCOUNTS_RO
            - PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_UPDATE
            - PERMISSION_SFS_ACCOUNT_ADMIN_ACCOUNTS_DELETE
