services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Softspring\AccountBundle\Form\Admin\:
        resource: '../../../Form/Admin/*'

    Softspring\AccountBundle\Controller\Admin\AccountsController:
        public: true
        tags: ['controller.service_arguments']